### ISSUE TITLE
Move land mask artifact to ClimaArtifacts

### ISSUE THREAD

**Issue by imreddyTeja** [CliMA/ClimaCoupler.jl#1025]
- [ ] Add land mask to ClimaArtifacts
- [ ] Remove mask_dataset_path()
- [ ] Remove sic and sst
- [ ] Add artifact to `experiments/ClimaEarth/Artifacts` and change usage
- [ ] consider removal of artifact_data() or relocation

**Comment by Sbozzolo** [comment]
There's a PR for land-sea mask: #1006 

We have to use the same land sea mask as the other models
