### ISSUE TITLE
Departure - Pending PRs

### ISSUE THREAD

**Issue by jb-mackay** [CliMA/ClimaCoupler.jl#106]
This issue is to document the different streams of work still unfinished/unmerged upon my departure and what I see as the steps needed to finish them.

**ClimaCore**
CliMA/ClimaCore.jl#793 - AbstractRemap and IdentityRemap
- Ready to merge, need to fix JET tests, see CliMA/ClimaCore#794 (unrelated to src code changes)

CliMA/ClimaCore.jl#811 - Extend ClimaCore remap interface for ClimaCoreTempestRemap
- Also dependent on CliMA/ClimaCore.jl#794, needs review from @simonbyrne @LenkaNovak 
- Need to decide if we will keep ClimaCoreTempestRemap as a separate package or move to ClimaCore src code
---

**ClimaCoupler**
#99 - Add remap to `coupler_put!`
- This is more of an experimental PR, might not be merged. Tests new storage for remap operators that makes building them easier.
- This depends on the above ClimaCore remapping abstractions
- Some thought needs to go into initializing these maps if we use this method.
- After talking with the NCAR team, it is clear that we will need more remap types besides conservative (bilinear and patch, e.g.). I think this PRs remap workflow could accommodate that if fields were marked by remap type during `coupler_add!` - this could set one of the type parameters of `CplField` which could be used for dispatch when applying operators.
- Mariana also shared that they apply remaps of the same type at the same time (e.g. do all patch remaps on fields, then do all conservative remaps together, etc). The current approach is very much the naive one in which a map is applied individually to a field. Perhaps a method could easily be inserted that collects the remaps when called during `put` and `get` and then applies them at the end of `push` or `pull`.

**Comment by LenkaNovak** [comment]
Relevant parts to be revisited in #211
