### ISSUE TITLE
Identify and document removable dependencies

### ISSUE THREAD

**Issue by juliasloan25** [CliMA/ClimaCoupler.jl#1075]
We want to go through the whole ClimaCoupler package and identify dependencies that we can easily remove. This will decrease compile time, and make sure that we're actually using all the dependencies we pull in.

### Environments to go through
- top-level Project
- experiments/ClimaEarth
- test
- experiments/ClimaCore
- docs

Part of https://github.com/CliMA/ClimaCoupler.jl/issues/1050

(see comments for dependencies we can remove)

**Comment by imreddyTeja** [comment]
Packages I found can be removed without implementing any new methods:
(note: I have not tried removing any of these and running)
### top level

- Artifacts

### experiments/ClimaEarth

- ClimaCorePlots
- Interpolations (indirectly dep) (needed for ClimaUtilitiesClimaCoreInterpolationsExt, which is never used -  check this , maybe in Project.toml for compat)
- Glob
- JLDL (indirectly dep)
- OrderedCollectrons (indirect dep)

### experiments/ClimaCore

- Thermodynamics (indirectly dependent)

### test
- Adapt (indirectly dep)
- CairoMakie
- ClimaAnalysis
- ClimaCorePlots 
- ClimaLand (indirectly dep,  maybe in Project for compat)
- ClimaTimeSteppers (indirectly dependent)
- ClimaUtilities (indirectly dependent,  maybe in Project for compat)
- Downloads (indirectly dependent,  maybe in Project for compat)
- GeoMakie
- Interpolations (indirectly dep) 
- IntervalSets (imported with using, need to check,  maybe in Project for compat)
- LinearAlgebra (indirect dep)
- OrderedColelctions (indirect dep)
- Plots
- PrettyTables (indirect dep,  maybe in Project for compat)
- Printf (indirect dep)
- SciMLBase (indirect dep, maybe in Project for compat)
- Statistics  (indirect dep)

### docs
- Pkg

Most of these are indirect dependencies/never imported, so I don't think removing them from Project.toml files wouldn't make compilation any faster. It seems like experiments/ClimaEarth has a lot of dependencies that are used for plotting and leaderboard.

**Comment by juliasloan25** [comment]
> Most of these are indirect dependencies/never imported, so I think removing them from Project.toml files wouldn't make compilation any faster.

It's a bummer that removing most of these won't help with compilation time. It would still be good to remove everything you identified so our environments only have what we need.

> It seems like experiments/ClimaEarth has a lot of dependencies that are used for plotting and leaderboard.

We could potentially move the plotting + leaderboard code into an extension that's only loaded for simulations where we want postprocessing. We can discuss and think about if this would be worth the effort.
