### ISSUE TITLE
Bug - coupler_driver.jl hangs when run with multithreading

### ISSUE THREAD

**Issue by juliasloan25** [CliMA/ClimaCoupler.jl#111]
## Describe the bug
When I open the Julia REPL with threading (using the flag --threads 8), then run coupler_driver.jl, the code hangs. This does not happen when I run the code without threading. See the screenshot below of the hanging behavior:

![clima_coupler_threads_hanging](https://user-images.githubusercontent.com/51397186/184445499-cc63e6d1-0be6-4515-bfcb-c6392b45e5e7.png)

## To Reproduce
Open the julia REPL using "julia --project --threads 8", then run the following:
```julia
include("coupler_driver.jl")
```

## System details
Julia version 1.7.3
macOS Monterey version 12.5

**Comment by LenkaNovak** [comment]
out of date
