### ISSUE TITLE
extend `write_exodus` to deal with distributed Topology

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaCoupler.jl#127]
We need to extend the ClimaCoreTempestRemap function:

```
write_exodus(::Any, !Matched::ClimaCore.Topologies.Topology2D; normalize_coordinates) 
```
to

```
write_exodus(::String, ::ClimaCore.Topologies.DistributedTopology2D{ClimaCommsMPI.MPICommsContext, ClimaCore.Meshes.EquiangularCubedSphere{ClimaCore.Domains.SphereDomain{Float32}, ClimaCore.Meshes.NormalizedBilinearMap}, Vector{CartesianIndex{3}}, Array{Int64, 3}, NamedTuple{(), Tuple{}}})
```
so that we can set boundary conditions from files onto the distributed topology. The easiest solution is to create a surrogate topology which is not distributed, collect data and distribute onto the model (distributed) topology.

**Comment by simonbyrne** [comment]
In general, I don't think we want to do the remapping as part of the distributed job.

Instead what I propose is the following:
1. Have an preprocessing script that does all the remapping, and saves it in our HDF5 format (in a single process).
2. In the main script, we load this directly.

The main challenge is making sure that the topology and quadrature used in 1. is the same as 2.
