### ISSUE TITLE
Update coupler for compatibility with ClimaAtmos v0.8.0

### ISSUE THREAD

**Issue by juliasloan25** [CliMA/ClimaCoupler.jl#187]
Update the coupler to use the newest version of ClimaAtmos ([v0.8.0](https://github.com/CliMA/ClimaAtmos.jl/releases/tag/v0.8.0)), and add necessary changes to the code.

**Comment by LenkaNovak** [comment]
#126 to be addressed in doing so

**Comment by LenkaNovak** [comment]
addressed by #197 : updated to ClimaAtmos 0.9.0
