### ISSUE TITLE
Update coupler to handle land albedo from file

### ISSUE THREAD

**Issue by juliasloan25** [CliMA/ClimaCoupler.jl#202]
ClimaLSM has been updated to read in surface albedo from a data file, rather than passing in a function for it as before (see ClimaLSM https://github.com/CliMA/ClimaLSM.jl/pull/125). 

The coupler should be updated to have a command line option `albedo_from_file` to specify whether we want to read in the albedo from a data file, with the default being true. The code relating to the bucket model in the coupler will also need to be updated to reflect the changes in ClimaLSM.

Addressed by #197

**Comment by LenkaNovak** [comment]
addressed by #197
