### ISSUE TITLE
Link up daily CI

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaCoupler.jl#22]
This is mainly for checking that the CI selection of test cases is still compatible with the fast-developing upstream packages.

**Comment by jb-mackay** [comment]
@LenkaNovak a Buildkite pipeline is now set up with #56. As discussed, it currently runs the sea breeze and it only tests that this simulation does not crash (currently only a 500s run). 

It is currently configured to run on pushes. We could also run it on a schedule if we would like to run longer simulations.

**Comment by LenkaNovak** [comment]
That's awesome, thanks @jb-mackay ! I wouldn't run it any longer, unless there's a reason (e.g. waiting for a flow instability to develop or comparing to a published benchmark, etc). We'll most likely run the baroclinic wave for 10s of days with the buckets + slabs once they're ready!
