### ISSUE TITLE
Add emissivity as a coupler field

### ISSUE THREAD

**Issue by juliasloan25** [CliMA/ClimaCoupler.jl#274]
We can add emissivity as an additional coupler field.

This will require first adding it as a parameter to the ClimaAtmos interface.

The coupler has defined a `surface_emissivity` function for the bucket model [here](https://github.com/CliMA/ClimaLSM.jl/blob/main/src/Bucket/bucket_parameterizations.jl#L21-L28), which we could make use of.

**Comment by LenkaNovak** [comment]
out of date
