### ISSUE TITLE
Repo cleanup: Merge dynamical_sea_ice

### ISSUE THREAD

**Issue by juliasloan25** [CliMA/ClimaCoupler.jl#314]
The `experiments/AMIP/moist_mpi_earth_dynamical_sea_ice` directory is no longer used, but has functionality we want to maintain. We should integrate these features into our main code and then delete this directory.

## To Do
- [ ] Move sea ice `slab_ice` functions to `AMIP/modular/components/ocean`
  - [ ] Verify that "slab" name is still accurate
- [ ] Add documentation (in wiki?) about the purpose of this directory for future reference
  - [ ] Read README.md for background
- [ ] Add tests for sea ice

**Comment by LenkaNovak** [comment]
This was done as part of #402
