### ISSUE TITLE
remove dependencies on component model data strucutres 

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaCoupler.jl#332]
- to make our code more modular and general we need to remove the remaining dependencies on component model data structures (e.g., `integrator.p.`) in the `src/` code (especially in `ConservationChecker`, where we need to add more general unit tests). `viz_explorer.jl` should be generalized as well.

# Components
- [ ] write wrapper function for instances where we call `integrator.p.` and move them to the `component/init...` files. The wrappers should live in the source code
  - e.g. generalize definitions of `get_slab_energy`
- [ ] revamp all relevant unit tests 

# QA
- [ ] physical and conservation tests should be unchanged
- [ ] no significant difference in performance

**Comment by juliasloan25** [comment]
this has been completed
