### ISSUE TITLE
O5.1.4 (coupler) Software Revamp for ClimaCoupler v0.1.0 Release

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaCoupler.jl#358]
# The Climate Modeling Alliance
### Purpose
We're currently preparing for our first release of the coupler. As part of this release, we want to make sure that the code is readable, documented, well tested, straightforward for new users, and generally high quality. This SDI involves improvements and refactoring of the codebase that will achieve these goals.

### Cost/Benefits/Risks
b: streamlining AMIP delivery, higher code quality
c: developer time

### People and Personnel
- Lead: @juliasloan25 
- Collaborators: @LenkaNovak @valeriabarra 
- Reviewers: 

### Components

- streamline and generalize coupler interface
- make sure documentation is thorough
- make sure testing is thorough

### Inputs

This SDI builds off of #276 and #359.

### Results and Deliverables

- able to run full AMIP simulation
- clean interface, which will be used to couple additional component models in the future
- high quality code (documentation, testing, readability, etc)

### QA
- no behavioural change (except a small change after #334)

### SDI Revision Log
31 July 2023 - updated by @juliasloan25 for accuracy
25 Sept 2023 - @juliasloan25 moved task breakdown to tasklists
20 Nov 2023 - some tasks moved to #516 to reduce content in this SDI and streamline v0.1.0 release (by @juliasloan25)
29 Feb 2024 - @juliasloan25 updated timelines

### Proposed Delivery Date
1 April 2024

```[tasklist]
### clean up coupler interface \[March 2024]
- [ ] #669
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/339
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/458
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/334
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/333
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/350
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/332
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/419
```

```[tasklist]
### improve code quality for release \[April 2024]
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/450
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/670
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/721
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/654
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/652
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/676
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/651
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/587
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/404
```

```[tasklist]
### miscellaneous \[April 2024]
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/693
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/653
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/667
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/533
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/537
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/553
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/525
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/449
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/427
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/524
- [ ] #507
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/441
- [x] #409
```

**Comment by LenkaNovak** [comment]
@juliasloan25 would it be possible to add #486 and #479 to this, since this is mainly interface work with no expected behavioral changes? Feel free to assign me to them for Q4.

**Comment by juliasloan25** [comment]
@LenkaNovak I added #486 under "prepare for release", and added #479 to #516
