### ISSUE TITLE
Add `up_deps.jl` script to automate/streamline updating dependencies

### ISSUE THREAD

**Issue by valeriabarra** [CliMA/ClimaCoupler.jl#409]
We should have an `up_deps.jl` similar to the one in ClimaAtmos and other CliMA repos (see, e.g., [up_deps.jl](https://github.com/CliMA/ClimaAtmos.jl/blob/main/.dev/up_deps.jl)), so that we can streamline and automate the update of dependencies instead of doing it manually, which is more error prone and tedious.

**Comment by LenkaNovak** [comment]
Thanks, @valeriabarra! This is related to the software release issue #358 so I'll tag it there. Note that some of the older examples (e.g. sea-breeze) are dependent on older packages, so I would only automate updating the Project only for the `AMIP/` case in the `experiments/` folder.
