### ISSUE TITLE
Reformulate `ConservationChecker`

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaCoupler.jl#419]
`ConservationChecker` is the last module dependent on component model specific data structures (e.g. integrator.u.... ). 

- [ ] remove dependencies on data structures in `ConservationChecker` module
- [ ] apply in unit tests
- [ ] apply in the AMIP driver

# QA
- [ ] no behaviour changes
- [ ] negligible changes/ improvements on performance

**Comment by juliasloan25** [comment]
this is completed via #436
