### ISSUE TITLE
Coupling on topography in a spherical domain

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaCoupler.jl#43]
## Purpose
- this contains all physical components for the AMIP run (though may leave TC out)

## Final Key Result
-  Smooth moist BW: atmos (full), land (full soil / [biophysics / canopy]), hydrology (full), ocean (prescribed), sea ice (prescribed), topography 

## Measure of success 
(literature comparison / conservation / performance benchmark)
- [ ] conserving tracers
- [ ] stable run
- [ ] similar performance to the standalone
- [ ] comparable to DCMIP chapter 2 cases (ClimaCore)

## Risks
- TC not fully integrated, but we can temporarily use vertical diffusion instead

## Design, Features and Dependencies
- [ ] approved design - N / A
- [ ] land-ocean mask (no topography)
- [ ] topography + all the above
    - [x] ClimaCore topography incl tests: [CC-pr667](https://github.com/CliMA/ClimaCore.jl/pull/667)
    - [ ] ClimaAtmos driver
        - [ ] analytical topog
        - [ ] real topog
- [ ] documentation

## Driver PR(s)
- [ ] BC wave with aquamountains
- [ ] Full atmos + land bucket + sea ice + land/sea mask

## People
- Lead: @akshaysridhar 
- Collaborators: @simonbyrne @jb-mackay @LenkaNovak 
- Reviewers: ??

## Ideal delivery date
- May 18 2022

**Comment by akshaysridhar** [comment]
https://github.com/CliMA/ClimaCore.jl/pull/667 In progress (bors check pending)

**Comment by LenkaNovak** [comment]
ready to deploy using ClimaAtmos when ready
