### ISSUE TITLE
update comms_ctx setting to match atmos

### ISSUE THREAD

**Issue by juliasloan25** [CliMA/ClimaCoupler.jl#444]
mpi comms context specification has diverged from Atmos. We need to follow ClimaAtmos approach

### To Do
- [ ] copy atmos comms_ctx init function ([here](https://github.com/CliMA/ClimaAtmos.jl/blob/47420ff0edfa1bb391085cc4ae3e0b83055c567b/src/solver/type_getters.jl#L658C2-L692)) to coupler
  - add to src/Utilities.jl
  - don't include `Logging`- or `NVTX`-related lines
- [ ] add "device" option to `experiments/AMIP/cli_options.jl`
  - update [cli_options](https://github.com/CliMA/ClimaCoupler.jl/blob/main/experiments/AMIP/cli_options.jl#L84) for command line arg 
  - we should have the same choices and default that atmos has [here](https://github.com/CliMA/ClimaAtmos.jl/blob/47420ff0edfa1bb391085cc4ae3e0b83055c567b/config/default_configs/default_config.yml#L117-L119)

**Comment by LenkaNovak** [comment]
@juliasloan25 I presume this is outdated?
