### ISSUE TITLE
Enable broadcasting with the same spaces and different instances

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaCoupler.jl#45]
Change error "Broacasted spaces are the same ClimaCore.Spaces type but not the same instance" [here](https://github.com/CliMA/ClimaCore.jl/blob/main/src/Fields/broadcast.jl#L110-L111) to a warning, needed for assigning new fields when coupling.

**Comment by jb-mackay** [comment]
Addressed in [CC #640](https://github.com/CliMA/ClimaCore.jl/pull/640) - figuring out how to circumvent the JET tests before merging.

**Comment by LenkaNovak** [comment]
Ok nice! Depending on whether this is a huge deal in CC (I see last time #604 updated was 9 days ago), we may want to circumvent it with a temporary local fix... or just keep coding clunkily with `parent`. What do you reckon?

**Comment by jb-mackay** [comment]
I'll make it a priority to find help resolving #640 asap. In the meantime, perhaps the best option is to extend/overwrite the error method locally. That was most of our code is ready to go when the changes is made and we won't have to go back to change `parent` calls.

**Comment by LenkaNovak** [comment]
Perfect, thanks @jb-mackay ! 🚀

**Comment by jb-mackay** [comment]
Closed by https://github.com/CliMA/ClimaCore.jl/pull/640.

To disable the error, we must extend the following method as shown here:
```julia
import ClimaCore.Fields
Fields.allow_mismatched_diagonalized_spaces() = true
```
