### ISSUE TITLE
Investigate new instability in mid-resolution AMIP benchmark

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaCoupler.jl#460]
Unconverged surface fluxes arise after the last series of upgrades, after ~120 sim days. This needs thorough investigation.

## Builds
- [Benchmark longrun fails](https://buildkite.com/clima/climacoupler-longruns/builds/229#018b026f-f1b3-4f60-81a4-45f8b19b298a) after 120d with [this](https://github.com/CliMA/ClimaCoupler.jl/blob/ln/topo-amip-longrun/config/longrun_configs/amip_longrun_target_orig.yml) configuration, though this used to run 140d+
- [August benchmark w/o CO2](https://buildkite.com/clima/climacoupler-longruns/builds/239) with [this](https://github.com/CliMA/ClimaCoupler.jl/blob/ln/topo-amip-longrun/config/longrun_configs/amip_longrun_target.yml) config
  - NB Atmos internal flags may have changed 
  - w/o CO2 - fails after 60d [build](https://buildkite.com/clima/climacoupler-longruns/builds/239#018b266b-5e6e-4c38-baa5-1c08311d532b )
  - [running prior](https://buildkite.com/clima/climacoupler-reports/builds/70#0189f4d8-42b8-4602-b751-320abcf82a77)
- Emulating atmos aquaplanet in coupled and not coupled scenario - [atmos yml config](https://github.com/CliMA/ClimaAtmos.jl/blob/main/config/longrun_configs/longrun_aquaplanet_rhoe_equilmoist_nz63_0M_55km_rs35km_clearsky_tvinsolation.yml)
  -  [w CO2](https://buildkite.com/clima/climacoupler-longruns/builds/238#018b264a-67d7-4bc9-a133-dc64481aad8c) - crash 5d
  - [w/o CO2](https://buildkite.com/clima/climacoupler-longruns/builds/239#018b266b-5e71-4eb0-a34e-0dd31c9922c4) - crash 10d 
  - uncoupled - both w CO2 & without still running

- long runs with different UFs ... coming up
- [spin up](https://github.com/CliMA/ClimaCoupler.jl/issues/474) of `new_target` dominated by tropical convection... this was resolved by using less abrupt initial conditions in the surface. 

## Findings
- maxiter may be an issue
- Better stability may be achievable with other UFs (Businger rn) - use FDScheme if so
- coarse benchmarks expected to be inaccurate, since dz_1 =  500m
- LSM - ppt fluxes opposite to convention; ~~possibly an extra E term in melt~~
- W and sigma S can become negative : e.g. [here](https://github.com/CliMA/ClimaLSM.jl/blob/main/src/standalone/Bucket/Bucket.jl#L512) the evaporative flux and snow fraction are based on the previous timestep
  - #472
- #470 
- may need to dss P_liq and P_snow
- even when calculating flux at atmos substeps e_tot is not conserved.
- atmos calls [this ts](https://github.com/CliMA/Thermodynamics.jl/blob/96f3bcff0b029882a1228643b883117d1fd6313e/src/states.jl#L283-L312) with maxiter 3 and rtol 0.003. Seems overly restrictive and fails with seemingly ok states. 
- current atmos T_init_sfc seems to be quite extreme and crashes most coarse runs
- using the same T_init as atmos + constant SST in the slab ocean breaks
  - [x] T is set properly - but still crashes ([build 275](https://buildkite.com/clima/climacoupler-longruns/builds/275))
  - [x] try `update_surface_conditions!` from the coupler in the model update 
    - [x] prescribing T_sfc etc crashes (still conserving) [build](https://buildkite.com/clima/climacoupler-longruns/builds/277)
    - [x] `update_surface_conditions!` without changing the initial `ts` , but still calculating fluxes outside at `dt_cpl` [build](https://buildkite.com/clima/climacoupler-longruns/builds/278)
    - [x] stepping from within atmos [build](https://buildkite.com/clima/climacoupler-longruns/builds/279)
  - [x] check all other MOST parameters are consistent - z0m,b
  - [x] local runs
    - [x] standalone atmos - nocouple
    - [x] standalone atmos - 400s couple; fluxes during Atmos stepping, no update sim -> identical to the above
    - [x] standalone atmos - 400s couple; fluxes during Atmos stepping, with update sim T -> identical to the above
    - [x] standalone atmos - 400s couple; fluxes during Atmos stepping, with update sim T, alpha -> identical to the above (with alpha = 0.38)
    - [x] coupled atmos - dt_cpl=400s; fluxes during dt_cpl, with update sim T, alpha, constant ocean -> small qualitative differences (e.g. F_turb_energy at 10d spin up): 
![Screen Shot](https://github.com/CliMA/ClimaCoupler.jl/assets/38083334/5f548494-92ab-456e-834e-cb994db98545)
    - [x] coupled atmos - dt_cpl=400s; fluxes during dt_cpl, with update sim T, alpha, sluggish bucket
![Screen Shot](https://github.com/CliMA/ClimaCoupler.jl/assets/38083334/045c3e18-c9f4-4838-a976-995106edef7e)
    - [x] increasing the thermal heat capacity of the bucket brings it closer to the aquaplanet
  - [x] initialization stage checked for proper field exchange

## Components
- [x] general callbacks - this allows easier checkpointing at an arbitrary interval. #482 
- [x] #477
  - [x] integration hierarchy
  - [x] longrun hierarchy, re-add snow, fix ice mask update, add topo, check insolation inconsistency

## Next steps
- topo runs seem to break at ~130days, thermal structure is not quite correct, also seen in atandalone atmos runs. More physical investigation needed: #485 
- add better diagnostics to CI pipeline

**Comment by akshaysridhar** [comment]
See also buildkite #1906

**Comment by LenkaNovak** [comment]
Closes Phase 1 Milestone https://github.com/CliMA/ClimaCoupler.jl/issues/389
