### ISSUE TITLE
truncate `@warn` in gray radiation `update_field`

### ISSUE THREAD

**Issue by juliasloan25** [CliMA/ClimaCoupler.jl#462]
truncation warning in AMIP CI: https://buildkite.com/clima/climacoupler-ci/builds/1882#018b1699-f2aa-4627-81a1-68961fa34414

this comes from the `@warn` statement here: https://github.com/CliMA/ClimaCoupler.jl/blob/main/experiments/AMIP/modular/components/atmosphere/climaatmos_init.jl#L112

solution: add `maxlog=10` arg to `@warn` call

closed by #456

**Comment by LenkaNovak** [comment]
Thanks @juliasloan25 for catching this one!
