### ISSUE TITLE
race condition in land albedo read

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaCoupler.jl#470]
This only happens for some specifications of the MPI setup as [here](https://buildkite.com/clima/climacoupler-longruns/builds/251). Currently, we get around this using [this fix](https://github.com/CliMA/ClimaCoupler.jl/commit/ca49a4100e85f09250c21755446069733330a3ed)

[This](https://github.com/CliMA/ClimaCoupler.jl/blob/ln/longruns-nwmi3/experiments/AMIP/modular/components/land/bucket_init.jl#L191C1-L203C82) needs to be removed once land is fixed.

**Comment by juliasloan25** [comment]
A fix for this race condition is made in ClimaLSM v0.4.0. #502 updated to use that version and removed this fix in ClimaCoupler, closing this issue
