### ISSUE TITLE
new_target issues

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaCoupler.jl#474]
- using this() config

## Terraplanet
![atmos_states_264](https://github.com/CliMA/ClimaCoupler.jl/assets/38083334/2751ee04-3da0-4a39-a119-1f4622f7b839)
![lnd_terra](https://github.com/CliMA/ClimaCoupler.jl/assets/38083334/9b26add8-f8c8-4646-8976-6c6a1a4f9650)
![atm_terra](https://github.com/CliMA/ClimaCoupler.jl/assets/38083334/7158d64b-2ccd-4bcb-bf1b-379685aad463)
- upon crash:
![land_states_264](https://github.com/CliMA/ClimaCoupler.jl/assets/38083334/5657c452-9863-43f7-baba-c9f39c46bf6d)

## AMIP
- https://buildkite.com/clima/climacoupler-longruns/builds/263
- 
![land_states_263](https://github.com/CliMA/ClimaCoupler.jl/assets/38083334/22fbfa22-ada1-4833-83d2-5d320b36af48)
![atmos_states_263](https://github.com/CliMA/ClimaCoupler.jl/assets/38083334/da8ae353-c5fd-4543-b6d9-b102f5d3f0ea)

**Comment by akshaysridhar** [comment]
<img width="1281" alt="Coupled_AtmosModelOutput_Build263" src="https://github.com/CliMA/ClimaCoupler.jl/assets/43710045/eb3b7353-d670-475a-b152-4e64e48e0f7a">

**Comment by LenkaNovak** [comment]
outdated
