### ISSUE TITLE
Phase 2: Stabilizing long runs

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaCoupler.jl#485]
## Current problems
- our long runs with dynamic surface suffer from an unphysical thermal structure and thus global circulation
- limited baroclinic instability, the atmosphere is too stable, most likely too diffusive in mid-high latitude troposphere
- overly strong lapse rate near the surface (insufficiently diffusive)
- build: https://buildkite.com/clima/climacoupler-longruns/builds/312#018b763d-ff2a-4170-b45b-87424c52558f

<img width="667" alt="Screen Shot 2023-11-02 at 5 31 00 PM" src="https://github.com/CliMA/ClimaCoupler.jl/assets/38083334/2ade126f-7a5e-49ef-84b4-2106a28a432d">
<img width="539" alt="Screen Shot 2023-11-02 at 6 54 10 PM" src="https://github.com/CliMA/ClimaCoupler.jl/assets/38083334/483b7273-b922-40e5-9f59-05b43d4cbdea">

## ClimaAtmos specs / debug
- diffusivity (week Nov 6)
  - [x] fix long runs in Atmos [@Sbozzolo]
  - [x] exp decrease with height, from sfc ([build](https://buildkite.com/clima/climaatmos-longruns/builds?branch=ln%2Ftst-diff-sfc)) and above 950hPa ([build](https://buildkite.com/clima/climaatmos-longruns/builds?branch=ln%2Ftst-diff))  [@LenkaNovak ] (see below)
  - [x] #509
  - [x] #510
  - [x] Investigate non-conservation in ClimaAtmos + implement checks in CI https://github.com/CliMA/ClimaAtmos.jl/issues/2458

## ClimaCoupler specs / debug
- equilibrated state with slab ocean
  - [x] #513
  - [x] check energy surface fluxes balances against observations
  - [x] #511
  - [x] #512
  - [x] #514
- versioning / updating (once physical issues resolved)
  - [x] update to ClimaAtmos 0.16.3 [@juliasloan25] https://github.com/CliMA/ClimaCoupler.jl/pull/502
  - [x] fix conservation after #556 (#https://github.com/CliMA/ClimaCoupler.jl/issues/568)
    - following params of [this run](https://github.com/CliMA/ClimaCoupler.jl/blob/7b860c23161b34810cdb41d86459ae44ab6fc423/config/longrun_configs/amip_target_topo.yml) 
  - [x] #515

## Arising issues to fix
- https://github.com/CliMA/ClimaCoupler.jl/issues/472
- https://github.com/CliMA/ClimaCoupler.jl/issues/470
- https://github.com/CliMA/ClimaCoupler.jl/issues/484
- #604

**Comment by akshaysridhar** [comment]
Build 312: Standalone atmos run (clearsky, monin-obukhov surface scheme, time varying insolation) Averaged over days (100-300) at 10-day output frequency. 
![Uploading Build312_Standalone_Atmos_AP_Clearsky_TVInsolation.png…]()

**Comment by akshaysridhar** [comment]
Build 312: Coupled atmos run (clearsky, monin-obukhov surface scheme, time varying insolation) Averaged over days (100-200) at 5-day output frequency.
<img width="1077" alt="Build312_NewTarget_ClearskyTVInsolation" src="https://github.com/CliMA/ClimaCoupler.jl/assets/43710045/3c0e3e79-abae-4c40-b87d-d1e38dc52d7c">

**Comment by szy21** [comment]
What is the difference in the standalone and coupled atmosphere run, and what is the albedo in these simulations?

**Comment by LenkaNovak** [comment]
standa

> What is the difference in the standalone and coupled atmosphere run, and what is the albedo in these simulations?

standalone = ClimaAtmos does the stepping and flux calculation (no coupler)
coupler = full AMIP (except topography and EDMF)

Albedo for standalone is 0.38 I believe, and AMIP reads this from a file. We get similar results for idealized albedo as a function of latitude.

**Comment by LenkaNovak** [comment]
Here are results from the build with exponential decrease of CE from the sfc: [build #1231](https://buildkite.com/clima/climaatmos-longruns/builds?branch=ln%2Ftst-diff-sfc)) (similar results for runs where C_E is constant to 950hPa, then exponentially decreasing)
NB: `C_E = CE_0 * exp(-((1e5 - p)/1e4)^2)`

day 100 zonal-mean snapshot (similar for day 180): 
<img width="315" alt="Screen Shot 2023-11-08 at 4 44 06 PM" src="https://github.com/CliMA/ClimaCoupler.jl/assets/38083334/fb156998-a757-41a6-8189-3af649ecc859">

data: 
- `/central/scratch/esm/slurm-buildkite/climaatmos-longruns/1231/climaatmos-longruns/tvinsolation_diff1/day100.0.hdf5`
- `/central/scratch/esm/slurm-buildkite/climaatmos-longruns/1231/climaatmos-longruns/tvinsolation_diff4/day100.0.hdf5`

@akshaysridhar , would it be possible to output the above diagnostics for these please? 

Next suggested steps: 
- try coupled runs with higher diffusivity (+ more granular analysis of sfc flux balance, why is the lw_up radiative flux so strong over the dynamic surface?) NB: diff of ~5m2/s is comparable to the axisymmetric experiments in [Walker and Schneider 05](https://agupubs.onlinelibrary.wiley.com/doi/pdf/10.1029/2004GL022304)
- implement the FMS diffusivity that's dependent on Ri (less diffusion at poles, more diffusion at low latitudes) - as in [Frierson et al 06](https://journals.ametsoc.org/view/journals/atsc/63/10/jas3753.1.xml)
- if still needed, try BM relaxation scheme

**Comment by akshaysridhar** [comment]
@LenkaNovak See https://github.com/CliMA/ClimaAtmos.jl/tree/as/frierson-diff for the updates w.r.t Frierson et al. (2006) Ri dependent boundary layer parameterization.I'm having some local test run issues but I expect to be able to resolve these soon.

**Comment by szy21** [comment]
This very old [branch](https://github.com/CliMA/ClimaAtmos.jl/tree/zs/jh/qe_moist_convection) has an implementation of Betts-Miller that is ~85% done, in case you need it.

**Comment by LenkaNovak** [comment]
Perfect, thank you!

**Comment by akshaysridhar** [comment]
> ## Standalone only
> 
> Here are results from the build with exponential decrease of CE from the sfc: [build #1231](https://buildkite.com/clima/climaatmos-longruns/builds?branch=ln%2Ftst-diff-sfc)) (similar results for runs where C_E is constant to 950hPa, then exponentially decreasing) NB: `C_E = CE_0 * exp(-((1e5 - p)/1e4)^2)`
> 
> day 100 zonal-mean snapshot (similar for day 180): <img alt="Screen Shot 2023-11-08 at 4 44 06 PM" width="315" src="https://user-images.githubusercontent.com/38083334/281582061-fb156998-a757-41a6-8189-3af649ecc859.png"> <img alt="Screen Shot 2023-11-08 at 5 35 27 PM" width="316" src="https://user-images.githubusercontent.com/38083334/281588410-89884605-5862-4d52-babb-e807dd6a80af.png">
> 
> data:
> 
>     * `/central/scratch/esm/slurm-buildkite/climaatmos-longruns/1231/climaatmos-longruns/tvinsolation_diff1/day100.0.hdf5`
> 
>     * `/central/scratch/esm/slurm-buildkite/climaatmos-longruns/1231/climaatmos-longruns/tvinsolation_diff4/day100.0.hdf5`
> 
> 
> @akshaysridhar , would it be possible to output the above diagnostics for these please?
> 
> Next suggested steps:
> 
>     * try coupled runs with higher diffusivity (+ more granular analysis of sfc flux balance, why is the lw_up radiative flux so strong over the dynamic surface?) NB: diff of ~5m2/s is comparable to the axisymmetric experiments in [Walker and Schneider 05](https://agupubs.onlinelibrary.wiley.com/doi/pdf/10.1029/2004GL022304)
> 
>     * implement the FMS diffusivity that's dependent on Ri (less diffusion at poles, more diffusion at low latitudes) - as in [Frierson et al 06](https://journals.ametsoc.org/view/journals/atsc/63/10/jas3753.1.xml)
> 
>     * if still needed, try BM relaxation scheme

Diff 1 Directory (Build 1231) (Day 180 avg)
<img width="1078" alt="TV_Insolation_Diff1_180" src="https://github.com/CliMA/ClimaCoupler.jl/assets/43710045/bc5bfbd7-f269-4436-a15a-92c0d8c56a48">

Diff 4 Directory (Build 1231) (Day 200-280 avg)
<img width="1077" alt="TV_Insolation_Diff4_200-280" src="https://github.com/CliMA/ClimaCoupler.jl/assets/43710045/3b406093-123d-4947-96af-983c9a8d2bee">

**Comment by szy21** [comment]
This recent [paper](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2023MS003736) uses an idealized model with RRTMG, no convection scheme, Frierson vertical diffusion, and slab ocean. It would be a good reference for us to compare. There are differences in details about insolation and greenhouse gases between our setup and theirs. Not sure if they are important, but even if they are, it should be straightforward to modify our setup. I'll check if I can get the data from the model.

**Comment by LenkaNovak** [comment]
# Constant diffusivity coupled runs (180d, start date 1 March):
- AMIP
  - crashed after day 20 [build](https://buildkite.com/clima/climacoupler-longruns/builds/364#018bc647-66fb-4445-8a83-0e84225f6733)
- Slab ocean
  - large seasonal variations, unrealistic circulations, lagged thermal response (sfc T)
![Screen Shot 2023-11-13 at 9 52 52 AM](https://github.com/CliMA/ClimaCoupler.jl/assets/38083334/c123b8ec-db17-4ca2-9013-71b04f61d0ef)

- fixed SST, bucket
  - more realistic
  - bucket
![Screen Shot 2023-11-13 at 9 52 23 AM](https://github.com/CliMA/ClimaCoupler.jl/assets/38083334/e9458c18-4c13-41fd-829b-649cebe2158c)

- Diags: 
![Screen Shot 2023-11-13 at 9 46 21 AM](https://github.com/CliMA/ClimaCoupler.jl/assets/38083334/6bcc35f6-e278-4000-bbb8-b6bb45f56809)

**Comment by LenkaNovak** [comment]
# AMIP with increased diffusivity
- `K_E x 4` and `K_E x 2` yielded similar results (more extreme for the former)
- evolving surface too cold (and dry) at the poles and too warm (and wet) at the equator
- lapse rate excessive in the tropics, very stable at the poles up to 1km
- both crash at day 120 (peak summer)

<img width="406" alt="Screen Shot 2023-11-14 at 6 08 13 PM" src="https://github.com/CliMA/ClimaCoupler.jl/assets/38083334/65460a49-e368-4a3c-9b08-2a82a4468f44">







-

**Comment by LenkaNovak** [comment]
#  Slab ocean with increased diffusivity

- `K_E x 4` crashed at 40d  and `K_E x 2` did not crash (ran to 320d)
- higher diffusivity causes the high latitude temperature to be too warm, jets and eddies are more distorted / banded and also much stronger (less extreme lapse rate), superrotation

<img width="357" alt="Screen Shot 2023-11-14 at 6 54 22 PM" src="https://github.com/CliMA/ClimaCoupler.jl/assets/38083334/7ae101f3-1cea-46a0-98f9-65630300d876">

# Next / current status
- higher diffusivity makes the tropic less unstable but the poles less stable. This points to the need for the Ri-dependent diffusivity
- we also checked the surface fluxes (rad and turbulent) against observations and these seem to be reasonable, except that the latent heat release is too high over land (max: 150W/m2 v 75W/m2) and potentially too low over the ocean (max: 100W/m2 v 150W/m2)
- implement the FMS diffusivity that's dependent on Ri (less diffusion at poles, more diffusion at low latitudes) - as in [Frierson et al 06](https://journals.ametsoc.org/view/journals/atsc/63/10/jas3753.1.xml)
- BM relaxation scheme
