### ISSUE TITLE
Enhance AMIP and NCEP paperplots

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaCoupler.jl#517]
We want to improve out artifacts from AMIP runs to make them easier to customize (use Makie), more comparable to the NCEP plots (interpolate to pressures) and more informative (add more useful variables). These plots will serve as a validationmetric for CI in our Buildkite pipelines and as a debugging tool.

# Current status

The `mode_name = amip` runs currently produce
<img width="918" alt="Screen Shot 2023-11-21 at 8 51 42 PM" src="https://github.com/CliMA/ClimaCoupler.jl/assets/38083334/4928d251-a7ec-49b5-8f9f-79b079236bad">
<img width="916" alt="Screen Shot 2023-11-21 at 8 51 29 PM" src="https://github.com/CliMA/ClimaCoupler.jl/assets/38083334/c53fd03b-ef03-489a-b5d2-6c8f445748e2">

These can be obtained by running [coupler_driver_modular.jl](https://github.com/CliMA/ClimaCoupler.jl/blob/main/experiments/AMIP/modular/coupler_driver_modular.jl) e.g. with [this](https://github.com/CliMA/ClimaCoupler.jl/blob/main/config/model_configs/coarse_single_modular_ft64_hourly_checkpoints_co2.yml) configuration. 

# To do
- [ ] use Makie instead of Plots e.g. as in [here](https://github.com/CliMA/ClimaAtmos.jl/blob/765bbda92963d7e0b663a075a9241ca3aa63c21a/post_processing/plot/plot_helpers.jl#L11)
- [ ] use pressure instead of height (z) as a vertical coordinate
- [ ] add more diagnostics [e.g. plots here](https://github.com/CliMA/ClimaCoupler.jl/issues/485)

**Comment by juliasloan25** [comment]
no longer relevant after switch to ClimaDiagnostics.jl/ClimaAnalysis.jl in https://github.com/CliMA/ClimaCoupler.jl/pull/953
