### ISSUE TITLE
MPI AMIP occasional hang

### ISSUE THREAD

**Issue by juliasloan25** [CliMA/ClimaCoupler.jl#538]
Our MPI AMIP run is hanging almost every time it's run.

It looks like the error originated in the PR where we updated dependencies https://github.com/CliMA/ClimaCoupler.jl/pull/535, which updated from ClimaCore v0.10 to v0.11 and also removed a pin for HDF5 at 1.12. That branch had the first hangs, though some commits hung and others passed. This branch was merged on 12/6.

Hangs on [this line](https://github.com/CliMA/ClimaCoupler.jl/blob/main/src/Regridder.jl#L335), where `ClimaCore.InputOutput.read_field` is called.

Edit: We've discovered that the issue is coming from memoizing Grids using a WeakValueDict, which was introduced in ClimaCore v0.11.0 See ClimaCore issue [#1589](https://github.com/CliMA/ClimaCore.jl/issues/1589) for more details. A fix will need to be implemented in ClimaCore.

### Examples of failure on buildkite
- [debug branch 2298 (has useful print statements)](https://buildkite.com/clima/climacoupler-ci/builds/2298#018cd097-0dbe-4d22-bc9d-dc1333139e2c)
- [dep updates PR 12/5 2208](https://buildkite.com/clima/climacoupler-ci/builds/2208)
- [dep updates PR 12/6 2223](https://buildkite.com/clima/climacoupler-ci/builds/2223#018c40b2-d596-4bbf-ae4e-c57216a67182)
- [dep updates PR 12/6 2220](https://buildkite.com/clima/climacoupler-ci/builds/2220)
- [on main 12/7 2229](https://buildkite.com/clima/climacoupler-ci/builds/2229#018c41cb-fba6-4b5b-b7ef-1660dd6e7aaa)
- [depot branch 12/8 2237](https://buildkite.com/clima/climacoupler-ci/builds/2237#_)
- this run [passed](https://buildkite.com/clima/climacoupler-ci/builds/2281), then [failed](https://buildkite.com/clima/climacoupler-ci/builds/2299) when re-run without any changes to the code.
- same error in MPI BCReader and MPI Regridder tests, [debug branch 1/4 2311](https://buildkite.com/clima/climacoupler-ci/builds/2311#_)

### Debugging notes
- increased `slurm_mem` for MPI AMIP job from 16GB to 32GB
- updated pipeline to match ClimaCore's: increased `JULIA_MAX_NUM_PRECOMPILE_FILES` from 50 to 100; added `slurm_mem: 80G` to init environment step; removed `SLURM_KILL_BAD_EXIT: 1`
- exits with error 137 (out of memory), but increasing memory from 16GB to 32GB didn't prevent hang
- downgraded ClimaCore 0.11.7 -> 0.11.3 (still hangs)
- downgraded ClimaCore 0.11.7 -> 0.10.56, ClimaAtmos 0.17 -> 0.16.3, Insolation 0.80 -> 0.6.0, RRTMGP -> 0.9.3
  - (I just wanted to downgrade ClimaCore but had to do them all)
  - this [passed](https://buildkite.com/clima/climacoupler-ci/builds/2335)!!!!!!!! the breaking change may have been made in ClimaCore v0.11.0 - 0.11.3. The only HDF5-related changes were made in 0.11.0 so it's probably something there

**Comment by Sbozzolo** [comment]
Here's another instance: https://buildkite.com/clima/climacoupler-ci/builds/2240#018c4c0d-9f07-476c-9858-8c4314e90476

**Comment by simonbyrne** [comment]
Will see what I can dig up on this run: https://buildkite.com/clima/climacoupler-ci/builds/2321
