### ISSUE TITLE
Accumulated Variables

### ISSUE THREAD

**Issue by jb-mackay** [CliMA/ClimaCoupler.jl#55]
This issue is intended as a place to keep track of all variables that will need accumulation in the ESM. Please add a comment if you are working with such a term when setting up a coupled model.

Specify:
1. The physical quantity being shared
2. The sending model
3. The receiving model
4. Any other relevant info (e.g. links to `rhs!` where the quantity is computed)

**Comment by trontrytel** [comment]
For coupling between the 0-moment microphysics in atmosphere and the land model we will need to sum the total sink of total water. 
1. S_rhoq_tot
2. Atmos
3. Land

**Comment by LenkaNovak** [comment]
implemented
