### ISSUE TITLE
Stable prescribed CO2, topo, sea ice and SST + diagnostic EDMF simulation

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaCoupler.jl#574]
A demonstration of this run in the Buildkite longruns pipeline.

**Comment by szy21** [comment]
June TOA radiative flux for reference:
![image](https://github.com/CliMA/ClimaCoupler.jl/assets/11598433/06f70e8b-1e5c-4e8e-bc06-0d39a321e682)
![image](https://github.com/CliMA/ClimaCoupler.jl/assets/11598433/abde7a6c-e8af-4670-8382-f401c9865cd5)
