### ISSUE TITLE
Implement a more realistic ocean surface albedo

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimaCoupler.jl#577]
Currently, the ocean surface albedo is assumed to be a constant (0.06). In reality, the ocean surface albedo depends on the solar zenith angle and surface slope (which depends on the wind speed). See [Cox and Munk](https://escholarship.org/uc/item/1p202179) for a good overview. The figure shows the ocean surface albedo derived from ~20 year average surface radiative fluxes from CERES EBAF (mean clear-sky upward SW / mean clear-sky downward SW at the surface, i.e., insolation weighted albedo). It would be good to implement a more realistic ocean surface albedo.
![image](https://github.com/CliMA/ClimaCoupler.jl/assets/11598433/bb5e6079-51a6-4e38-be29-2d928308ef80)

Short-term solution: Use a simple function of solar zenith angle and surface slope, fitted to observations. 

- [x] A function of solar zenith angle and surface slope: [Jin et al. 2011 ](https://opg.optica.org/oe/fulltext.cfm?uri=oe-19-27-26429&id=225797), multiple regression with more parameters, can use the parameters in the paper directly, probably fits the observation better. Slightly harder to implement.
  - https://github.com/CliMA/ClimaAtmos.jl/issues/2677

Long-term solution (can be turned into an SDI later): 

- [ ] Use a more principled scheme which has been implemented in RRTMG. reference: https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2020JC016958 https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2023MS003702

**Comment by tapios** [comment]
I think a good path forward here may be this:

* Implement right away the regression formulas for direct and diffuse surface albedo from [Jin et al. (2011) ](https://opg.optica.org/oe/fulltext.cfm?uri=oe-19-27-26429&id=225797), ignoring the relatively small interior scattering (which depends on chlorophyll). This is just two regression formulas, plus Fresnel reflection formulas---just a few lines of code. This would give us reasonable results quickly. 
* In the coming weeks, implement the more principled approach of [Wei et al. (2021)](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2020JC016958), which uses the diffuse radiation component we have explicitly. Code for this is available at [Zenodo](https://zenodo.org/records/10038654) and just would need to be translated.

**Comment by szy21** [comment]
The regression formula for albedo has been implemented. We still need to compare the results with observations. The current scheme we have may suffice for the near future. I'll move the more principle scheme to a separate issue and we can tackle that later.

**Comment by szy21** [comment]
Here is ~200-day average clear sky albedo from this [build](https://buildkite.com/clima/climacoupler-longruns/builds/656#018f1ad5-055b-4534-b67f-11b5075cd06a)
![image](https://github.com/CliMA/ClimaCoupler.jl/assets/11598433/067059ba-c176-41a7-a8b5-b584728d6a1b). 
The values are a bit too large compared to observations, but the overall pattern looks good. It is not plotting the same time period, and I think we can tune some parameters to match observations better, so I will close this issue for now. I will open a new issue for the more principled scheme when we plan to do it.
