### ISSUE TITLE
Sort config alphabetically

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaCoupler.jl#595]
## Components
- [x] alphabetical rearrangement of all configs
- [x] change name of the gpu run to preclude race conditions
- [x] fix path to the atmos standalone run in longruns

## Future
- could we apply this to climaformat.jl?

**Comment by szy21** [comment]
The alphabetization is nice, but for atmos I find it easier for development when we order configs in physics groups - e.g. numerics, radiation, convection, microphysics, especially when the config file is long. This way people who work on a specific component can easily change the configs they want. But it may be different for the coupler, up to you:)

**Comment by LenkaNovak** [comment]
Hmm, I wonder if we could do something like you did for edmf with a prefix - e.g., `edmfx_upwinding`, so that we can sort alphabetically and order them in meaningful clusters at the same time? 🤔

**Comment by LenkaNovak** [comment]
alphabetical definitely makes our checking easier :)

**Comment by LenkaNovak** [comment]
No worries, we'll stick with the coupler only cases for now.
