### ISSUE TITLE
debug `allskywithclear` instability

### ISSUE THREAD

**Issue by juliasloan25** [CliMA/ClimaCoupler.jl#602]
In the latest set of dependency updates, https://github.com/CliMA/ClimaCoupler.jl/pull/598, our two shortruns using the `allskywithclear` radiation option have become unstable. For now, they've been changed to use `gray` radiation, but we should address the root cause of this and bring back `allsky` stability.

changed toml files to revert:
- [ ] config/model_configs/coarse_single_ft64_hourly_checkpoints_co2.yml
- [ ] config/model_configs/target_params_in_slab_test2.yml

cc @LenkaNovak @akshaysridhar

**Comment by LenkaNovak** [comment]
Follow up:
- local checks reverting TD to 11.2 still leads to instability after 2d 8h (slabplanet) - https://github.com/CliMA/Thermodynamics.jl/pull/185/files is not the culprit
- coupler and at mos config arguments pre post CA0.20 updates have not changed substantially
- `rayleigh_sponge: true`, `implicit_diffusion: true` and `approximate_linear_solve_iters: 2`,  `dt = 300s` did not help

**Comment by LenkaNovak** [comment]
The `allskywithclear` is now stable for 200d at the 100km target resolution with all AMIP configurations. [build](https://buildkite.com/clima/climacoupler-longruns/builds/649#_)

**Comment by juliasloan25** [comment]
@LenkaNovak should we change `coarse_single_ft64_hourly_checkpoints_co2.yml` and `target_params_in_slab_test2.yml` back to use `allskywithclear` radiation now that it's stable?

**Comment by LenkaNovak** [comment]
Yes, we can change these (or add new ones), but the important one was for `allskywithclear` work with the target run. Note that it is unclear whether `allskywithclear` should work with the lower resolutions, since atmos doesn't have comparable tests.
