### ISSUE TITLE
Use DocStringExtensions

### ISSUE THREAD

**Issue by jb-mackay** [CliMA/ClimaCoupler.jl#64]
Improve documentation quality and robustness to future code changes by using [DocStringExtensions.jl](https://juliadocs.github.io/DocStringExtensions.jl/latest/). Particularly:
`FIELDS`, `SIGNATURES`, and `EXPORTS`.

**Comment by jb-mackay** [comment]
This PR can also update the doc format to satisfy the [CliMA Documentation Policy](https://github.com/CliMA/policies/wiki/Documentation-Policy)

**Comment by LenkaNovak** [comment]
@valeriabarra , this should help with the docstring task in #205
