### ISSUE TITLE
Add remapping to `coupler_put!`

### ISSUE THREAD

**Issue by jb-mackay** [CliMA/ClimaCoupler.jl#65]
Currently it is not possible to map to an exchange or intermediary grid -- any field `put!` in the coupler lives on the space of the simulation that puts it there.

This is because of the current way the mapping is set up which uses a tag (`write_sim`) to specify the source space/sim when remapping. This tag also (as the name suggests) indicates which simulation has write permissions to that coupled field. 

Perhaps the right solution is to remove the double usage of `write_sim` and add another tag like "`space_name`" which would be part of the remap operator name.

Adding remapping to the `put!` side of things creates symmetry and more flexibility for what grids the coupling takes place on. It creates the potential that there could be a coupler-owned field in memory, rather than the coupler only registering pointers.

_Originally posted by @jb-mackay in https://github.com/CliMA/ClimaCoupler.jl/issues/58#issuecomment-1159262614_

**Comment by LenkaNovak** [comment]
to be addressed in #211
