### ISSUE TITLE
Auto-building remap operations & Coupled Sim Init

### ISSUE THREAD

**Issue by jb-mackay** [CliMA/ClimaCoupler.jl#67]
Initializing a coupled simulation needs to be designed such that the actual remap operator construction can be hidden.

The init process might look something like:
1. Init all component simulations with existing standalone code
2. Init coupled simulation struct
3. Init maps using boundary spaces of each model
4. Reinit component simulations with updated coupled fields

**Comment by LenkaNovak** [comment]
To be addressed in #211
