### ISSUE TITLE
Use ClimaUtilities for ingesting data from files

### ISSUE THREAD

**Issue by Sbozzolo** [CliMA/ClimaCoupler.jl#715]
`ClimaUtilities` 0.1.2 comes with a large collection of useful modules. For `ClimaCoupler`, `TimeVaryingInput` and `SpaceVaryingInput` are probably the most relevant. 

The `TimeVaryingInput` module essentially implements `BCReader.jl` and `Regridder.jl` (but does it so in a highly modular way). While `TimeVaryingInput` is not perfectly equivalent at the moment (e.g., it doesn't support land fraction), I hope we can centralize the development and focus our efforts on ClimaUtilities for the sharable infrastructure. This should reduce maintenance burden for several Clima packages (in ClimaLand, switching to ClimaUtilities removed 2500 lines of code).

See documentation: https://clima.github.io/ClimaUtilities.jl/dev/

**Comment by juliasloan25** [comment]
this is being used now
