### ISSUE TITLE
Change to use new ClimaParameter handling

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaCoupler.jl#72]
We should apply the new clima parameter handling. An example of how to do this is in [this PR](https://github.com/CliMA/ClimaLSM.jl/pull/68).

A success metric for closing this issue involves:
 - Having a centralized module for where clima parameters from dependency packages can be accessed (see, e.g., [CloudMicrophysics.jl's Parameters module](https://github.com/CliMA/CloudMicrophysics.jl/blob/e32b555cb8e958a5dc852883ec4718a9e5b63f92/src/Parameters.jl), which forwards methods for handling thermodynamic variables).
 - Removing Land.jl's dependence on CLIMAParameters (i.e., `using CLIMAParameters` / `import CLIMAParameters` does not live in `Land/src/`).
 - All parameters that were previously obtained from CLIMAParameters methods are obtained from the CLIMAParameters [toml file](https://github.com/CliMA/CLIMAParameters.jl/blob/488a615476370b88a68aa5273c40bc18dbcf4cb8/src/parameters.toml)

It may be more efficient to clean up / remove any old / unused code / tests before applying these changes since it's a bit involved.

**Comment by LenkaNovak** [comment]
refer to #70
