### ISSUE TITLE
Artifact failures during Land and Atmos input file spec

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaCoupler.jl#732]
https://buildkite.com/clima/climacoupler-longruns/builds/543#018ebf35-dc1a-401e-84bb-4568707ecd7e

fails always for start date 19790228. This may be resolved by using ClimaUtilities in ClimaLSM. 

https://buildkite.com/clima/climacoupler-longruns/builds/545#018ebf46-a502-420f-bd3c-8d02e426c7de

fail sporadically, here for start date 19790227 (problem with topo_elev_dataset_path). This may be resolved by using ClimaUtilities in ClimaAtmos.

**Comment by juliasloan25** [comment]
We haven't seen this bug in months, and have switched land artifacts to use ClimaArtifacts, so I'm assuming this is fixed
