### ISSUE TITLE
Fix 20% error in GPU energy tracking

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaCoupler.jl#735]
# experiments 
- [no rad](https://buildkite.com/clima/climacoupler-longruns/builds/559#018ec05a-3a0b-4734-9637-c9552edb0e91)
  - tested [FT32](https://buildkite.com/clima/climacoupler-longruns/builds/584#018ece23-a714-4655-82d5-d10c60cd665e) and [FT64](https://buildkite.com/clima/climacoupler-longruns/builds/585#018ece2c-f7c4-4f41-b54e-38167636d775)
    - FT32: divergence begins after q_sfc and the first flux calculation (GPU fewer digits as expected) 
    - FT64: divergence not until 2nd step in coupling loop, O(-8) for ρ_sfc and F_turb_energy, O(-4) for F_turb_moisture, none for P_net or T_S -> most likely cumulative differences due to stepping nonlinearly atmos ts state (not unexpected)
   
CPU v GPU plots (ocean and land)

<img width="1185" alt="Screen Shot 2024-04-11 at 11 42 18 AM" src="https://github.com/CliMA/ClimaCoupler.jl/assets/38083334/95b46e64-555d-4147-a2a5-01bcd326ed19">

CPU v GPU plots (ocean, no land)
<img width="1203" alt="Screen Shot 2024-04-09 at 1 58 13 PM" src="https://github.com/CliMA/ClimaCoupler.jl/assets/38083334/cfe1a157-074e-4685-b170-37d546264d00">

- e.g. FT32: 
  - total_diff_CPU = -5.17f20
  - total_diff_GPU = -9.00f21
  - (i.e., plotting ok)

- [no rad, no turb fluxes](https://buildkite.com/clima/climacoupler-longruns/builds/560#018ec069-a66f-4d58-aad7-712eba39f801)
  - energy conserving but different behavior - GPU 2-daily jumps (though these are close to FT limit)

- [changing initial condiitons T_init = 290K, z0=5e-4](https://buildkite.com/clima/climacoupler-longruns/builds/586) blows up both CPU ad GPU

- [set no mom flux and round turbulent fluxes](https://buildkite.com/clima/climacoupler-longruns/builds/594#018ecf66-c375-4db3-99b3-caa9a9b77876) - similar divergence

- [no rad, no land and round turb](https://buildkite.com/clima/climacoupler-longruns/builds/597) - good conservation

- constant turbulent energy flux = 100W/m2 (all other fluxes = 0)](https://buildkite.com/clima/climacoupler-longruns/builds/604#018ed2ae-7ff0-4395-8f7f-f757a97abc17) clearly show that there is a bug in GPU energy transfer to lang (all other components are identical)
<img width="1183" alt="Screen Shot 2024-04-12 at 9 32 05 AM" src="https://github.com/CliMA/ClimaCoupler.jl/assets/38083334/13e0aba9-ae78-4eec-9b67-78417913f80e">

- inspecting the final saved states of the above case ([build](https://buildkite.com/clima/climacoupler-longruns/builds/610#_)), shows that the bucket sim is (except some floating precision errors) identical for both cpu and gpu
```
using JLD2
using ClimaCore
using ClimaTimeSteppers
using ClimaCore: InputOutput
using ClimaComms
using Statistics

using ClimaCore: InputOutput
using ClimaComms

simtime = 1728000
bkite_path = "."

file_name = "checkpoint_BucketSimulation_$simtime.hdf5"
device = ClimaComms.CPUSingleThreaded()
const comms_ctx = ClimaComms.context(device)
hdfreader = InputOutput.HDF5Reader(file_name, comms_ctx)
Y_new_cpu = InputOutput.read_field(hdfreader, "model_state")
Base.close(hdfreader)

# same for gpu_day100.0.hdf5
file_name = "gpu_checkpoint_BucketSimulation_$simtime.hdf5"
device = ClimaComms.CPUSingleThreaded()
const comms_ctx = ClimaComms.context(device)
hdfreader = InputOutput.HDF5Reader(file_name, comms_ctx)
Y_new_gpu = InputOutput.read_field(hdfreader, "model_state")
Base.close(hdfreader)


# julia> Y_new_gpu.T |> extrema
# (267.6576642973032, 300.0)

# julia> Y_new_cpu.T |> extrema
# (267.6576642973032, 300.0)

# julia> Y_new_gpu.W |> extrema
# (6.499999999992324, 6.500000000007676)

# julia> Y_new_gpu.W |> extrema
# (6.499999999992324, 6.500000000007676)

# julia> Y_new_gpu.σS |> extrema
# (0.0, 0.0)

# julia> Y_new_cpu.σS |> extrema
# (0.0, 0.0)

# test the following

function get_energy(state)
    # required by ConservationChecker
    e_per_area = zeros(axes(state.W))
    ClimaCore.Fields.bycolumn(axes(state.T)) do colidx
        e_per_area[colidx] .=
        2e6 .* mean(state.T[colidx]) .* 10
    end

    e_per_area .+=
        -(2834400 - 2500800).*
        1000 .* state.σS
    return e_per_area
end

sum(get_field(Y_new_gpu)) 
# 2.912976799071399e24

sum(get_field(Y_new_cpu))
# 2.9129767990713955e24
```

- this means there is a problem with the get_field(bucket_sim::BucketSimulation, ::Val{:energy}) function

- replacing Statistics.mean / soil_depth with column_integral_definite fixes the problem! [build](https://buildkite.com/clima/climacoupler-longruns/builds/618#018edf89-9424-42dc-8827-8b315e3f167e). This is fixed by the current PR.

# Suggestions for future enhancements

- investigate the why mean operates differently on GPU and CPU (Perhaps ClimaCore needs an extension?) ... this is because GPU ignores colidx -  see comment below
  -  Spaces.column - https://github.com/CliMA/ClimaAtmos.jl/blob/e3d8c1b828f175424a02aeec0a991184cbd751ab/test/utilities.jl#L225 - but this is not performant (kernel on GPU per column)
  - use column_mapreduce 
- quantitatively, the conservation is still worse for the GPU cases [build](https://buildkite.com/clima/climacoupler-ci/builds/3394), but this is only slight and not totally unexpected, since GPU and CPU are not bitwise reproducible. Still, this is something to keep in mind when addressing #594

# Components in this PR

- [x] fix land energy calculation, which alleviates the 20% error in the logger
- [x] increase slightly the allowed error (from 1e-3 to 2e-3). This was arbitrary in the first place and is used to track the rough conservation until we can track energy sinks and sources in Atmos (see #594)

**Comment by charleskawczynski** [comment]
Maybe we should just get rid of `bycolumn`, because it's functionally different between CPU and GPU (https://github.com/CliMA/ClimaCore.jl/issues/1609).

**Comment by charleskawczynski** [comment]
Maybe we can replace this with `Operators.column_mapreduce!`? If it's not performant critical code, we could use `Spaces.column`

**Comment by LenkaNovak** [comment]
Thank you, @charleskawczynski . See #736
