### ISSUE TITLE
Use 4xA100 to achieve > 1SYPD for target EDMF AMIP

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaCoupler.jl#740]
Since [gpu_amip_topo_target_diagedmf](https://github.com/CliMA/ClimaCoupler.jl/blob/main/.buildkite/longruns/pipeline.yml#L291) is our current target, we want to run it on the faster nodes: either clima's A100 or new-central's V100 / H100.

# Results
Running on Clima should be sufficient.

## clima A100:
- current driver, 4 GPUs [build](https://buildkite.com/clima/climacoupler-longruns/builds/630) SYPD ~ 1.51
- current driver  w/o coupler diagnostics (still with atmos diags), 4 GPUs [build](https://buildkite.com/clima/climacoupler-longruns/builds/631#018eef5f-81f0-4396-abf8-f9c93924a2b8) SYPD ~ 1.63

## new-central P100
- current driver, 1 GPU [build](https://buildkite.com/clima/climacoupler-longruns/builds/627#018eeed0-d717-4342-a92d-d85509ea6eb4) SYPD ~ 0.23
- current driver, 4 GPUs [build](https://buildkite.com/clima/climacoupler-longruns/builds/628) - memory timeout

## Note
- currently this run crashes (saturation adjustment) after ~90-140 days (non deterministic).

## Components in PR
- [x] move gpu_amip_topo_target_diagedmf to clima
- [x] increase t_end to 90d
- [x] spilt clima pipeline init from individual runs, so we can run the multiple runs on clima
- [x] remove concurrency block, which was slowing down the clima init, even though the depots are in different locations

**Comment by Sbozzolo** [comment]
What's the issue with the P100?

**Comment by LenkaNovak** [comment]
Apparently they're too slow and we're using this run as an SYPD benchmark.

**Comment by Sbozzolo** [comment]
If you are interested, this build https://buildkite.com/clima/climacoupler-longruns/builds/628 can be fixed by asking more memory per CPU

**Comment by LenkaNovak** [comment]
That's useful to know, thanks! We'll still run the benchmark on the A100 (as requested by the OKR), but this will be useful for the scaling tables (Cc'ing @juliasloan25 ).

**Comment by LenkaNovak** [comment]
Update: 

The above results are for 200km resolution. 

For 100km resolution SYPD on 4xA100: between 0.8 and 1.5 (see [builds](https://buildkite.com/clima/climacoupler-longruns/builds?branch=ln%2F100km-test)). This is partly dependent on whether we use coupler/atmos diagnsotics, but removing diagnostics didn't always lead to better SYPD. We also see a large variability between runs of the same config, and even within one simulation. More thorough investigation is being performed as part of https://github.com/CliMA/ClimaAtmos.jl/issues/2914. And we will be presenting a like-for-like comparison and scaling as part of https://github.com/CliMA/ClimaCoupler.jl/issues/663. 

Notes:
- when server was busy, got [these](https://buildkite.com/clima/climacoupler-longruns/builds/647#018f08c1-d68a-4a12-b744-a6e1010cebd2) memory errors, some nodes kept running
- 100km edmf run runs to 90d without breaking [build](https://buildkite.com/clima/climacoupler-longruns/builds/645#018f082d-1b27-4321-bbda-b7dcbb5f30a0)

**Comment by LenkaNovak** [comment]
Now achieving 1.082 https://buildkite.com/clima/climacoupler-longruns/builds/668#018f325b-a6d2-4c2d-b67f-1416484fda11

**Comment by Sbozzolo** [comment]
> Now achieving 1.082 https://buildkite.com/clima/climacoupler-longruns/builds/668#018f325b-a6d2-4c2d-b67f-1416484fda11

While it should be reasonably accurate, I would encourage you not to look at the SYPD printed by the progress log. That is an estimate and does not reflect the actual SYPD in some cases (e.g, first iterations, when callbacks/diagnostics are called).

**Comment by LenkaNovak** [comment]
Very true, but for avoidance of doubt, [this](https://buildkite.com/clima/climacoupler-longruns/builds/668#018f325b-a6d2-4c2d-b67f-1416484fda11) run shows we can achieve at least 380sim days in 1 day of walltime.
