### ISSUE TITLE
Update longruns for ClimaAtmos config changes

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaCoupler.jl#800]
For example, `gpu_aquaplanet_diagedmf.yml` no longer exists, leading to breaking coupled longruns [here](https://buildkite.com/clima/climacoupler-longruns/builds/690#018f9390-3439-49a8-9193-e7418a556d8a).

**Comment by LenkaNovak** [comment]
@szy21 , presumably this just needs to be changed to `aquaplanet_diagedmf.yml`, or do you know if there have been any config changes from the previous version of that Atmos config file? Maybe some of the toml arguments?

Cc'ing @juliasloan25 for visibility.

**Comment by szy21** [comment]
Ah, it is from this PR which should be a breaking change: https://github.com/CliMA/ClimaAtmos.jl/pull/3008. I'm not very familiar with the recent filename changes, @charleskawczynski should know more. Maybe we can document which configs are used in the coupler, so that we can know whether a PR is a breaking change?

**Comment by charleskawczynski** [comment]
Ah, yeah, I didn't realize that the coupler is using the ClimaAtmos yaml configs. That PR simply unifies some yaml files, so changing the filename should fix it. I'll add the breaking label to that PR.

**Comment by juliasloan25** [comment]
#### ClimaAtmos configs used in ClimaCoupler (as of 20 May 2024)
- config/model_configs/aquaplanet_diagedmf.yml
- config/longrun_configs/longrun_aquaplanet_rhoe_equil_55km_nz63_allsky_diagedmf_0M.yml
- config/longrun_configs/longrun_aquaplanet_rhoe_equil_55km_nz63_clearsky_0M_earth.yml
- config/longrun_configs/longrun_aquaplanet_rhoe_equil_55km_nz63_clearsky_0M.yml
- config/longrun_configs/longrun_aquaplanet_dyamond.yml
cc @szy21
