### ISSUE TITLE
Stabilize EDMF longrun after updating to ClimaAtmos = "0.24"

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaCoupler.jl#809]
This now fails (sat. adjustment error) at around 100d. [build](https://buildkite.com/clima/climacoupler-longruns/builds/691)

- check default diagnostics at: `/scratch/clima/slurm-buildkite/climacoupler-longruns/691/climacoupler-longruns/experiments/ClimaEarth/output/amip/gpu_amip_target_topo_diagedmf/clima_atmos`

**Comment by szy21** [comment]
The diagnostic edmf run passed in the latest build. Other simulations are tracked in different issues.
