### ISSUE TITLE
add hierarchy data visualizations

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaCoupler.jl#814]
Visualization infrastructure for the paper

## components
- [x] climate plots
- [x] interpolation to pressure coordinates
- [x] data management from a series of runs
- [x] implement in CI

These generate plots such as in [in this issue](https://github.com/CliMA/ClimaCoupler.jl/issues/760). 

Note: A lot of the choices here are hard coded for the purposes of the hierarchy paper, but perhaps something similar (especially the z to pressure conversion) could be implemented in ClimaAnalysis if it isn't already. (@Sbozzolo)

**Comment by Sbozzolo** [comment]
Yes, most of what you have in the PR is already available, except for the conversion to pressure coordinates, which I was planning on adding when someone needed it. 

If this infrastructure is for a specific paper, maybe we can have it in a separate folder, alongside with the Manifest needed to reproduce the results? Having it here in src that this has to be updated and maintained and would not offer guarantees of reproducibility for those that wish to use the script to reproduce the paper.

**Comment by LenkaNovak** [comment]
Yess, Julia and I were just Slacking about that :-D
