### ISSUE TITLE
No output in netcdf when cpu run breaks

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimaCoupler.jl#858]
See this run for example: https://buildkite.com/clima/climacoupler-longruns/builds/725#01901fb8-0260-48d1-9915-52e06361ed91 (This run times out).

**Comment by Sbozzolo** [comment]
The NetCDF output is correctly produced, see `/central/scratch/esm/slurm-buildkite/climacoupler-longruns/725/climacoupler-longruns//experiments/ClimaEarth/output/amip/amip_target_topo_diagedmf_cpu/clima_atmos/output_0000` on the cluster.

**Comment by szy21** [comment]
> /central/scratch/esm/slurm-buildkite/climacoupler-longruns/725/climacoupler-longruns//experiments/ClimaEarth/output/amip/amip_target_topo_diagedmf_cpu/clima_atmos/output_0000

If you do `ncdump -h [any nc file]` in that folder, you will see the time dimension has 0 length. The simulation runs for ~60 days.

**Comment by Sbozzolo** [comment]
Okay, I see it now. Should be easy to work around.
