### ISSUE TITLE
Broadcasting in Sea Breeze Coupled Boundary Conditions

### ISSUE THREAD

**Issue by jb-mackay** [CliMA/ClimaCoupler.jl#86]
In the sea breeze coupled boundary condition definition, the following code block that builds the atmosphere face fields on the surface boundary space. This is currently necessary because the local geometry data is not the same since the atmosphere fields are at the first level with height > 0 while the surface boundary fields have height zero.

```julia
windspeed_boundary = Fields.Field(Fields.field_values(windspeed_boundary), axes(p.T_sfc))
θ_boundary = Fields.Field(Fields.field_values(θ_boundary), axes(p.T_sfc))
ρ_boundary = Fields.Field(Fields.field_values(ρ_boundary), axes(p.T_sfc))
```

Discussing with @simonbyrne, a temporary solution would be to introduce a function that extrapolates the values at the surface level of field1 and puts them on the local geometry of field2. This is essentially doing what the above does but conceptually formalizes this and puts it in one place that we can later change.

**Comment by jb-mackay** [comment]
Perhaps, add @LenkaNovak's `swap_space!` to src.

https://github.com/CliMA/ClimaCoupler.jl/blob/fdbdbc149f5f45720aefe028d20dd253545db050/experiments/AMIP/moist_mpi_earth/coupler_utils/general_helper.jl#L17-L21

**Comment by LenkaNovak** [comment]
We will use `swap_space` or it's successor upon the interface revamp. :)
