### ISSUE TITLE
check fields regridded with TempestRemap

### ISSUE THREAD

**Issue by juliasloan25** [CliMA/ClimaCoupler.jl#860]
We found some issues with our TempestRemap code in the albedo (see https://github.com/CliMA/ClimaCoupler.jl/issues/764). We also need to check if other fields regridded with TR (e.g. surface fluxes) look okay or not.

**Comment by juliasloan25** [comment]
Using the `config/ci_configs/gpu_amip_albedo_temporal_map` setup, I see the following fields for input data after they've been read in and regridded:
- SST_init
![SST_init](https://github.com/CliMA/ClimaCoupler.jl/assets/51397186/803b061d-0f74-4e6a-b9e3-ef245a88046b)

- SIC_init
![SIC_init](https://github.com/CliMA/ClimaCoupler.jl/assets/51397186/1012b03d-626c-4fd3-82a3-3c723a43844d)

- land_area_fraction
![land_area_fraction](https://github.com/CliMA/ClimaCoupler.jl/assets/51397186/691a8fbd-62b0-43a6-950b-2269d1956c53)

- CO2_init 
![CO2_init](https://github.com/CliMA/ClimaCoupler.jl/assets/51397186/9e41da1d-7641-47d6-83b5-d72b51a4e2c6)

The first three look good. The CO2 looks unusual, and we have `minimum(CO2_init) == maximum(CO2_init) == 0.00037866`, but I want to plot the NetCDF input before regridding to see if this comes from the regridding.

**Comment by szy21** [comment]
CO2 might be ok. I remember seeing strange patterns when plotting something uniform, as it comes up with a default colorbar with a very small range.

**Comment by juliasloan25** [comment]
All of the regridded files look fine, so we can close this issue
