### ISSUE TITLE
Land-sea mask is low resolution

### ISSUE THREAD

**Issue by Sbozzolo** [CliMA/ClimaCoupler.jl#936]
The land sea mask we are currently using is only 64x64 points (in long-lat).

It is also a different land sea mask than ClimaLand.

**Comment by akshaysridhar** [comment]
A reasonable initial step towards improvements might be to use data provided in https://www.ncl.ucar.edu/Applications/Data/#cd under `landseamask.nc` which contains a 360x180 (lon-lat) grid with 4 masking categories:  
```
Global attributes
  title                = 1x1 Land-Sea Mask, 0=Ocean, 1=Land, 2=Lake, 3=Small Island, 4=Ice Shelf
  creation_date        = Thu May  6 10:51:06 MDT 2004
  source               = Based on Rand's Global Elevation and Depth Data, Modified Extensively
  source_web           = http://www.dss.ucar.edu/datasets/ds750.1/
  creator              = Adam Phillips, NCAR
```
We can collect information from even higher resolution datasets (following the Slack discussion) in a separate issue if necessary.

<img width="500" alt="Land-SeaMask_NCAR" src="https://github.com/user-attachments/assets/8db2dcf2-f175-4f8a-8cee-0a4bcf97f908">
