### ISSUE TITLE
Leaderboard test fails due to undownloadable artifact

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimaCoupler.jl#948]
This test was commented out in #946

**Comment by juliasloan25** [comment]
@szy21 do you have a link to the failure?

**Comment by szy21** [comment]
The closest one I can find is here: https://github.com/CliMA/ClimaCoupler.jl/actions/runs/10732954858/job/29765494405. (I might have deleted the artifact for this build, but the error would be something similar.)

**Comment by Sbozzolo** [comment]
@ph-kev, I assigned you here because this will be automatically fixed by closing #956
